<a href="https://colab.research.google.com/github/rushdishams/learn-with-rushdi/blob/main/pandas/Pandas%20Interview%205%20-%20Move%20Label%20Column%20or%20Target%20Variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

### How to move label column or target variable to a desired location/ position

1. Create a dataset or dataframe from scratch
2. Add labels or target variables to that dataset
3. Pop out the column which is label or target variable
4. Insert that popped out column into a desired location

In [5]:
import numpy as np
array = np.random.rand(10,10)

In [6]:
df = pd.DataFrame(array,
                  columns=list('abcdefghij'))

In [7]:
df.head(10)

,a,b,c,d,e,f,g,h,i,j
0,0.290809,0.534678,0.823877,0.487392,0.388625,0.284919,0.997848,0.904554,0.421850,0.891952
1,0.637366,0.948062,0.885182,0.766931,0.943070,0.948550,0.628128,0.685519,0.556954,0.116955
2,0.031383,0.569760,0.912749,0.575955,0.141766,0.308402,0.663624,0.066625,0.744462,0.233200
3,0.408309,0.815286,0.265520,0.890272,0.930028,0.087040,0.001169,0.652491,0.984217,0.785803
4,0.501281,0.103192,0.425136,0.224938,0.016046,0.470272,0.030715,0.210989,0.169483,0.262056
5,0.260554,0.630187,0.102665,0.076315,0.344040,0.290978,0.329882,0.659827,0.036591,0.939411
6,0.579607,0.992492,0.350004,0.174202,0.145907,0.249548,0.788311,0.958155,0.921879,0.883108
7,0.844173,0.853612,0.722131,0.927776,0.168870,0.377451,0.768178,0.159196,0.388560,0.620514
8,0.171339,0.930226,0.755435,0.203912,0.765759,0.585671,0.119601,0.506751,0.762003,0.469289
9,0.457730,0.390459,0.720194,0.970642,0.267255,0.128180,0.122004,0.405495,0.437969,0.334681

In [8]:
df['label'] = np.random.randint(2, size=10)

In [9]:
df.head(10)

,a,b,c,d,e,f,g,h,i,j,label
0,0.290809,0.534678,0.823877,0.487392,0.388625,0.284919,0.997848,0.904554,0.421850,0.891952,1
1,0.637366,0.948062,0.885182,0.766931,0.943070,0.948550,0.628128,0.685519,0.556954,0.116955,0
2,0.031383,0.569760,0.912749,0.575955,0.141766,0.308402,0.663624,0.066625,0.744462,0.233200,0
3,0.408309,0.815286,0.265520,0.890272,0.930028,0.087040,0.001169,0.652491,0.984217,0.785803,1
4,0.501281,0.103192,0.425136,0.224938,0.016046,0.470272,0.030715,0.210989,0.169483,0.262056,1
5,0.260554,0.630187,0.102665,0.076315,0.344040,0.290978,0.329882,0.659827,0.036591,0.939411,0
6,0.579607,0.992492,0.350004,0.174202,0.145907,0.249548,0.788311,0.958155,0.921879,0.883108,1
7,0.844173,0.853612,0.722131,0.927776,0.168870,0.377451,0.768178,0.159196,0.388560,0.620514,0
8,0.171339,0.930226,0.755435,0.203912,0.765759,0.585671,0.119601,0.506751,0.762003,0.469289,0
9,0.457730,0.390459,0.720194,0.970642,0.267255,0.128180,0.122004,0.405495,0.437969,0.334681,0

In [10]:
label = df.pop('label')

In [11]:
df

,a,b,c,d,e,f,g,h,i,j
0,0.290809,0.534678,0.823877,0.487392,0.388625,0.284919,0.997848,0.904554,0.421850,0.891952
1,0.637366,0.948062,0.885182,0.766931,0.943070,0.948550,0.628128,0.685519,0.556954,0.116955
2,0.031383,0.569760,0.912749,0.575955,0.141766,0.308402,0.663624,0.066625,0.744462,0.233200
3,0.408309,0.815286,0.265520,0.890272,0.930028,0.087040,0.001169,0.652491,0.984217,0.785803
4,0.501281,0.103192,0.425136,0.224938,0.016046,0.470272,0.030715,0.210989,0.169483,0.262056
5,0.260554,0.630187,0.102665,0.076315,0.344040,0.290978,0.329882,0.659827,0.036591,0.939411
6,0.579607,0.992492,0.350004,0.174202,0.145907,0.249548,0.788311,0.958155,0.921879,0.883108
7,0.844173,0.853612,0.722131,0.927776,0.168870,0.377451,0.768178,0.159196,0.388560,0.620514
8,0.171339,0.930226,0.755435,0.203912,0.765759,0.585671,0.119601,0.506751,0.762003,0.469289
9,0.457730,0.390459,0.720194,0.970642,0.267255,0.128180,0.122004,0.405495,0.437969,0.334681

In [12]:
df.insert(0, 'label', label)

In [13]:
df

,label,a,b,c,d,e,f,g,h,i,j
0,1,0.290809,0.534678,0.823877,0.487392,0.388625,0.284919,0.997848,0.904554,0.421850,0.891952
1,0,0.637366,0.948062,0.885182,0.766931,0.943070,0.948550,0.628128,0.685519,0.556954,0.116955
2,0,0.031383,0.569760,0.912749,0.575955,0.141766,0.308402,0.663624,0.066625,0.744462,0.233200
3,1,0.408309,0.815286,0.265520,0.890272,0.930028,0.087040,0.001169,0.652491,0.984217,0.785803
4,1,0.501281,0.103192,0.425136,0.224938,0.016046,0.470272,0.030715,0.210989,0.169483,0.262056
5,0,0.260554,0.630187,0.102665,0.076315,0.344040,0.290978,0.329882,0.659827,0.036591,0.939411
6,1,0.579607,0.992492,0.350004,0.174202,0.145907,0.249548,0.788311,0.958155,0.921879,0.883108
7,0,0.844173,0.853612,0.722131,0.927776,0.168870,0.377451,0.768178,0.159196,0.388560,0.620514
8,0,0.171339,0.930226,0.755435,0.203912,0.765759,0.585671,0.119601,0.506751,0.762003,0.469289
9,0,0.457730,0.390459,0.720194,0.970642,0.267255,0.128180,0.122004,0.405495,0.437969,0.334681